/**
 * Re-exports for backwards compatibility.
 * Prefer importing from `./walletListing`.
 */
export {
  WALLET_ID,
  WALLET_HOMEPAGE,
  WALLET_ICON,
  WALLET_METADATA_ICONS,
  WALLET_NATIVE_LINK,
  WALLET_UNIVERSAL_LINK,
  CUSTOM_WALLET,
  KURA_WALLET_ID,
  KURA_WALLET_HOMEPAGE,
  KURA_WALLET_ICON,
  KURA_WALLET_METADATA_ICONS,
  KURA_WALLET_NATIVE_LINK,
  KURA_WALLET_UNIVERSAL_LINK,
  KURA_CUSTOM_WALLET,
} from './walletListing';
