/**
 * Expo config plugin: adopt the UIKit UIScene life cycle on iOS.
 *
 * Starting with the iOS 27 SDK (Xcode 27), UIKit makes scene-lifecycle adoption
 * MANDATORY: an app built against that SDK whose Info.plist has no
 * `UIApplicationSceneManifest` is killed at launch with an EXC_BREAKPOINT in
 * `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption` — the white
 * splash → crash we hit on TestFlight. (Apple Technote TN3187.)
 *
 * The Expo SDK 54 prebuild template still emits the legacy
 * AppDelegate-creates-the-window startup, so we add the scene plumbing here:
 *   1. Declare a Default scene configuration pointing at our SceneDelegate.
 *   2. Drop a SceneDelegate.swift that ASSOCIATES the existing AppDelegate window
 *      with the connecting UIWindowScene (and forwards deep links).
 *   3. Register SceneDelegate.swift as a compiled source in the Xcode project.
 *
 * We deliberately keep AppDelegate.didFinishLaunching creating the window and
 * calling startReactNative untouched: expo-dev-launcher (Debug) asserts in
 * didFinishLaunching if `UIApplication.shared.delegate?.window` is nil, so the
 * window must already exist there. The SceneDelegate then re-parents that window
 * onto the scene, which is all the iOS 27 SDK requires.
 *
 * Harmless on the iOS 26 SDK (manifest is merely recommended) and runs on every
 * `expo prebuild`, so the fix survives native regeneration.
 */
const { withInfoPlist, withDangerousMod, withXcodeProject, IOSConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

function sceneDelegateSource() {
  return `import Expo
import React
import ReactAppDependencyProvider

// Generated by plugins/withIosSceneLifecycle.js — see that file for context.
// AppDelegate.didFinishLaunchingWithOptions still creates the UIWindow and boots
// React Native (expo-dev-launcher relies on that window existing in Debug). Here
// we re-parent that window onto the connecting UIWindowScene so the app adopts
// the UIScene life cycle required by the iOS 27 SDK (Apple Technote TN3187).
@objc(SceneDelegate)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }

    if let appDelegate = UIApplication.shared.delegate as? AppDelegate,
       let window = appDelegate.window {
      window.windowScene = windowScene
      self.window = window
      window.makeKeyAndVisible()
    }

    // Cold-start deep links: openURLContexts / continue are not called for the
    // launch event, so replay them through RCTLinkingManager here.
    if let url = connectionOptions.urlContexts.first?.url {
      RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
    }
    for userActivity in connectionOptions.userActivities {
      RCTLinkingManager.application(
        UIApplication.shared,
        continue: userActivity,
        restorationHandler: { _ in }
      )
    }
  }

  // Warm-start custom-scheme links (wallet redirects).
  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
  }

  // Warm-start Universal Links.
  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    RCTLinkingManager.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
`;
}

/** 1. Declare the scene manifest so UIKit knows we adopt the scene life cycle. */
function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });
}

/** 2. Write SceneDelegate.swift into the app source group. */
function withSceneDelegateFile(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const appDir = path.join(cfg.modRequest.platformProjectRoot, cfg.modRequest.projectName);
      fs.writeFileSync(path.join(appDir, 'SceneDelegate.swift'), sceneDelegateSource());
      return cfg;
    },
  ]);
}

/** 3. Add SceneDelegate.swift to the Xcode project's compile sources. */
function withSceneDelegateBuildFile(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const projectName = cfg.modRequest.projectName;
    const filepath = `${projectName}/SceneDelegate.swift`;

    if (!project.hasFile(filepath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project,
      });
    }

    return cfg;
  });
}

const withIosSceneLifecycle = (config) => {
  config = withSceneManifest(config);
  config = withSceneDelegateFile(config);
  config = withSceneDelegateBuildFile(config);
  return config;
};

module.exports = withIosSceneLifecycle;
